name: bingo_wholesale
description: Bingo Wholesale
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.1"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.0.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.4
  http: 0.13.5
  json_serializable: ^6.5.4
  sqflite: 2.0.3+1
  path_provider:
  auto_size_text:
  qr_flutter: ^4.0.0
  shimmer: ^2.0.0
  flutter_holo_date_picker: ^1.1.0
  loading_animation_widget: ^1.2.0+3
  image_picker: ^0.8.6
#  firebase_messaging: ^14.1.3
#  firebase_core:
#  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  multiple_search_selection: ^2.3.2
  dropdown_button2: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
  injectable_generator: ^1.5.4



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/login_design/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
